name: Tests

on:
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Enable Corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.15.3 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build (monorepo)
        run: pnpm -r build

      - name: Run CLI tests
        run: pnpm --filter polkadot-ui test

      - name: Run Registry tests
        run: pnpm --filter @polkadot-ui/registry test
